# Generated by Django 5.2.3 on 2025-07-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_hostel_user_delete_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel_user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
