# Generated by Django 5.2.3 on 2025-08-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='full_name',
        ),
        migrations.AddField(
            model_name='admin',
            name='first_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='admin',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
