# Generated by Django 5.2.3 on 2025-08-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_remove_admin_full_name_admin_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel_user',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='hostel_user',
            name='password',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
